#!/bin/sh

npm test

if test $(git diff --name-only dist | wc -l) != 0
then
	cat <<\EOF
Error: Not all the tracked files were ready for a push.

Maybe you were intentionally letting dist/ behind.

dist/ is tracked so the project could be imported from github.

    npm install "https://github.com/juanmanuelgg/bonapata-partes.git#branch-name" --save

If you know what you are doing you can disable this check using:

  git push --no-verify
EOF
	exit 1
fi