#!/usr/bin/env node
/**
 * Traido de https://gist.github.com/mklabs/1246769
 */
var npm = nrequire('npm');
if (npm)
    return npm.load(function (e, n) {
        this.commands.test(function (e) {
            process.exit(e ? 1 : 0);
        });
    });

// npm not installed locally, spawn process instead.
// basically the same, but less pretty.
var spawn = require('child_process').spawn,
    ch = spawn('npm', ['test']);

ch.stdout.pipe(process.stdout, { end: false });
ch.stderr.pipe(process.stderr);
ch.on('exit', function (code) {
    process.exit(code ? 1 : 0);
});

function nrequire(m) {
    var n;
    try {
        n = require(m);
    } catch (e) {
        console.log(
            'please, install ' +
                m +
                ' locally to be able to use it programmatically. will spawn process instead. \n'
        );
    }
    return n;
}