# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    # Puse una proteccion sobre main, ahora solo entra codigo a traves de pull_requests
    #    push:
    #        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 22
              uses: actions/setup-node@v5
              with:
                  node-version: 22
                  cache: 'npm'
            - run: npm i
            - run: npm run build --if-present
            - run: npm test
